<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes - Generated by Vemto
|--------------------------------------------------------------------------
|
| It is not recommended to edit this file directly. Although you can do so,
| it will generate a conflict on Vemto's next build.
|
*/

// Dashboard
Route::prefix('/dashboard')
    ->name('dashboard.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {
        Route::get('/users', App\Livewire\Dashboard\UserIndex::class)->name(
            'users.index'
        );

        Route::get(
            '/users/create',
            App\Livewire\Dashboard\UserCreate::class
        )->name('users.create');

        Route::get(
            '/users/{user}',
            App\Livewire\Dashboard\UserEdit::class
        )->name('users.edit');

        Route::get(
            '/pemeliharaans',
            App\Livewire\Dashboard\PemeliharaanIndex::class
        )->name('pemeliharaans.index');

        Route::get(
            '/pemeliharaans/create',
            App\Livewire\Dashboard\PemeliharaanCreate::class
        )->name('pemeliharaans.create');

        Route::get(
            '/pemeliharaans/{pemeliharaan}',
            App\Livewire\Dashboard\PemeliharaanEdit::class
        )->name('pemeliharaans.edit');

        Route::get(
            '/pemeriksaans',
            App\Livewire\Dashboard\PemeriksaanIndex::class
        )->name('pemeriksaans.index');

        Route::get(
            '/pemeriksaans/create',
            App\Livewire\Dashboard\PemeriksaanCreate::class
        )->name('pemeriksaans.create');

        Route::get(
            '/pemeriksaans/{pemeriksaan}',
            App\Livewire\Dashboard\PemeriksaanEdit::class
        )->name('pemeriksaans.edit');
    });

// API
Route::prefix('/api')
    ->name('api.')
    ->middleware(['auth:sanctum', config('jetstream.auth_session'), 'verified'])
    ->group(function () {});

// Site
Route::prefix('/')->group(function () {});

// Filament Panel
Route::prefix('/panel')
    ->name('panel.')
    ->group(function () {});
